### ISSUE TITLE
[BUG] RTV sometimes starts when only 1 player has issued a RTV

### ISSUE THREAD

**Issue by Kyli3Boi** [qawery-just-sad/surftimer-mapchooser#4]
**Describe the bug**
RTV sometimes starts when only 1 player has issued a RTV

**How To Reproduce**
Unsure as this happens at random

**Error Log**
I will attach as soon as i see another case of this happening so i can give you logs as close to when it happened

**Expected behavior**
Wait until correct number of players have voted before starting a RTV

**Screenshots**
![image](https://user-images.githubusercontent.com/64275139/85305833-e30f6400-b4ad-11ea-9af6-35b102c366f1.png)

**System Information:**
 - OS: Windows
 - Plugins List: 
01 "Admin File Reader" (1.10.0.6488) by AlliedModders LLC
  02 "SQL Admins (Prefetch)" (1.10.0.6488) by AlliedModders LLC
  03 "Admin Help" (1.10.0.6488) by AlliedModders LLC
  04 "Admin Menu" (1.10.0.6488) by AlliedModders LLC
  05 "AFK Manager" (4.3.0) by Rothgar
  06 "Anti-Flood" (1.10.0.6488) by AlliedModders LLC
  07 "Basic Chat" (1.10.0.6488) by AlliedModders LLC
  08 "Basic Comm Control" (1.10.0.6488) by AlliedModders LLC
  09 "Basic Commands" (1.10.0.6488) by AlliedModders LLC
  10 "Basic Info Triggers" (1.10.0.6488) by AlliedModders LLC
  11 "Basic Votes" (1.10.0.6488) by AlliedModders LLC
  12 "Client Preferences" (1.10.0.6488) by AlliedModders LLC
  13 "Command hider" (1.0) by Author zipcore Compiled by Playa
  14 "CS:GO Movement Unlocker" (1.0) by Peace-Maker
  15 "Discord API" (0.1.103) by Deathknife
  16 "Fun Commands" (1.10.0.6488) by AlliedModders LLC
  17 "Fun Votes" (1.10.0.6488) by AlliedModders LLC
  18 "SurfTimer MapChooser" (1.2) by AlliedModders LLC & SurfTimer Contributors
  19 "Momentum surf fix '2" (1.1.2) by GAMMA CASE
  20 "SurfTimer Nominations" (1.2) by AlliedModders LLC & SurfTimer Contributors
  21 "Paint!" (2.0) by SlidyBat
  22 "Player Commands" (1.10.0.6488) by AlliedModders LLC
  23 "Reserved Slots" (1.10.0.6488) by AlliedModders LLC
  24 "RNGFix" (1.1.2) by rio
  25 "SurfTimer Rock The Vote" (1.2) by AlliedModders LLC & SurfTimer Contributors
  26 "Block SM Plugins" (1.0.0) by Bara
  27 "SourceBans++: Admin Config Loader" (1.6.3) by AlliedModders LLC, SourceBans++ Dev Team
  28 "SourceBans++: Bans Checker" (1.6.3) by psychonic, Ca$h Munny, SourceBans++ Dev Team
  29 "SourceBans++: SourceComms" (1.6.3) by Alex, SourceBans++ Dev Team
  30 "SourceBans++ Discord Plugin" (1.1.0) by RumbleFrog, SourceBans++ Dev Team
  31 "SourceBans++: Main Plugin" (1.6.3) by SourceBans Development Team, SourceBans++ Dev Team
  32 "SourceBans++ Report Plugin" (1.6.3) by RumbleFrog, SourceBans++ Dev Team
  33 "SourceBans++: SourceSleuth" (1.6.3) by ecca, SourceBans++ Dev Team
  34 "ServerAdvertisements3" (3.1.4) by ESK0
  35 "Sound Commands" (1.10.0.6488) by AlliedModders LLC
  36 "SQL Admin Manager" (1.10.0.6488) by AlliedModders LLC
  37 "SurfTimer" (286) by Ace & olokos
  38 "SteamWorks Additive Glider" (1.0) by Kyle Sanderson
  39 "SteamWorks Update Check" (1.0b) by Kyle Sanderson
  40 "vote extend" (1.0)
 
- Mapchooser Version: 1.2

**Additional context**

**Comment by qawery-just-sad** [comment]
Please add plugins list

**Comment by Kyli3Boi** [comment]
Done

**Comment by qawery-just-sad** [comment]
For now i would recommend using [1.2.2](https://github.com/qawery-just-sad/surftimer-mapchooser/releases/tag/1.2.2)
If issue still occurs and there is no error logs then i have no idea.
Also fully restart the server after updating the plugin.

**Comment by Kyli3Boi** [comment]
Thank you, i have upgraded to 1.2.2 and rebooted the server. 

I will let you know if i get more reports of this

**Comment by stunslave** [comment]
Can confirm that this happens on Latest Release 1.2.2 and Dev version. 
It's very random, and hardly ever happens but it happens.

It happens more often when changing the Vote Requirements. (Points / Rank)

**Comment by Kyli3Boi** [comment]
I have also received a report of this happening again. Strangely enough on surf_pantheon again.

I have gone through all the logs and there is no errors...

**Comment by qawery-just-sad** [comment]
@stunslave can i get plugins list as well?

**Comment by qawery-just-sad** [comment]
@Kyli3Boi can you try to reproduce the issue with `"Command hider" (1.0) by Author zipcore Compiled by Playa` Disabled?
(sorry but not feeling well)

**Comment by Kyli3Boi** [comment]
Sure thing ill disable it and see how it goes

**Comment by qawery-just-sad** [comment]
99% sure it's some plugin on your end that is/was not compatible. Closing the issue.
